### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by coffmark** [Ryosukekamimura/HealthKit_Data_Collection#7]

**Comment by Ryosukekamimura** [comment]
![IMG_4636](https://user-images.githubusercontent.com/52638834/97796841-45495400-1c5a-11eb-97c8-46d9e27c3bc8.PNG)
<img width="576" alt="Screenshot 2020-11-01 15 49 41" src="https://user-images.githubusercontent.com/52638834/97796848-572af700-1c5a-11eb-9c30-a42fbdda5862.png">
